# Generated by Django 5.2.8 on 2025-11-24 12:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0002_tag_remove_review_tags_review_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('inappropriate', 'Inappropriate Content'), ('fake_account', 'Fake Account'), ('impersonation', 'Impersonation'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reported_users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('notify_on_follow', models.BooleanField(default=True)),
                ('notify_on_comment', models.BooleanField(default=True)),
                ('notify_on_like', models.BooleanField(default=True)),
                ('notify_on_mention', models.BooleanField(default=True)),
                ('notify_on_new_follower', models.BooleanField(default=True)),
                ('notify_on_chat_request', models.BooleanField(default=True)),
                ('notify_on_match_found', models.BooleanField(default=True)),
                ('show_spoilers', models.BooleanField(default=False)),
                ('mature_content', models.BooleanField(default=False)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('preferred_region', models.CharField(default='US', max_length=10)),
                ('autoplay_trailers', models.BooleanField(default=True)),
                ('theme_mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='auto', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_setting_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_settings_preferences',
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('most_watched_genre', models.JSONField(blank=True, default=dict)),
                ('favorite_decade', models.CharField(blank=True, max_length=10)),
                ('average_movie_length', models.IntegerField(default=0)),
                ('most_active_day', models.CharField(blank=True, max_length=10)),
                ('most_active_hour', models.IntegerField(blank=True, null=True)),
                ('total_likes_received', models.IntegerField(default=0)),
                ('total_comments_made', models.IntegerField(default=0)),
                ('current_watch_streak', models.IntegerField(default=0)),
                ('longest_watch_streak', models.IntegerField(default=0)),
                ('last_watch_date', models.DateField(blank=True, null=True)),
                ('movies_watched_percentile', models.FloatField(default=0.0)),
                ('reviews_written_percentile', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('most_liked_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reviews.review')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_stats',
            },
        ),
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, max_length=500)),
                ('blocked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blocked_users',
                'ordering': ['-blocked_at'],
                'unique_together': {('user', 'blocked_user')},
            },
        ),
        migrations.CreateModel(
            name='ReportedContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('review', 'Review'), ('post', 'Post'), ('comment', 'Comment')], max_length=20)),
                ('content_id', models.CharField(max_length=100)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('inappropriate', 'Inappropriate Content'), ('harassment', 'Harassment'), ('misinformation', 'Misinformation'), ('spoilers', 'Unmarked Spoilers'), ('copyright', 'Copyright Violation'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_reports_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reported_content',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'content_id'], name='reported_co_content_5bcc69_idx'), models.Index(fields=['status', '-created_at'], name='reported_co_status_ad5596_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('movie_watched', 'Movie Watched'), ('review_posted', 'Review Posted'), ('review_liked', 'Review Liked'), ('comment_posted', 'Comment Posted'), ('user_followed', 'User Followed'), ('movie_rated', 'Movie Rated'), ('watchlist_created', 'Watchlist Created'), ('achievement_earned', 'Achievement Earned'), ('session_created', 'Matching Session Created')], max_length=30)),
                ('related_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='user_activi_user_id_47a698_idx'), models.Index(fields=['activity_type', '-created_at'], name='user_activi_activit_b9defd_idx')],
            },
        ),
    ]
