# Generated by Django 5.2.8 on 2025-11-23 07:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_genres', models.JSONField(default=dict)),
                ('disliked_genres', models.JSONField(default=list)),
                ('preferred_runtime_min', models.IntegerField(default=80)),
                ('preferred_runtime_max', models.IntegerField(default=180)),
                ('prefer_recent_movies', models.BooleanField(default=True)),
                ('prefer_classic_movies', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendation_user_preferences',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('reason', models.CharField(choices=[('genre_match', 'Based on your favorite genres'), ('similar_users', 'Users like you enjoyed this'), ('trending', 'Trending now'), ('high_rated', 'Highly rated'), ('new_release', 'New release you might like')], max_length=50)),
                ('is_viewed', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendations',
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['user', '-score'], name='recommendat_user_id_8236a6_idx')],
                'unique_together': {('user', 'movie')},
            },
        ),
        migrations.CreateModel(
            name='SimilarityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'similarity_scores',
                'indexes': [models.Index(fields=['user_1', '-similarity_score'], name='similarity__user_1__4a1327_idx')],
                'unique_together': {('user_1', 'user_2')},
            },
        ),
    ]
