# Generated by Django 5.2.8 on 2025-11-23 15:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_alter_recommendation_movie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPreference',
            new_name='RecommendationPreference',
        ),
    ]
