# Generated by Django 5.2.8 on 2025-11-24 13:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=140)),
                ('selected_genres', models.JSONField(blank=True, default=list)),
                ('theme', models.CharField(blank=True, max_length=100)),
                ('release_year_min', models.IntegerField(blank=True, null=True)),
                ('release_year_max', models.IntegerField(blank=True, null=True)),
                ('max_runtime', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for participants'), ('active', 'Active (swiping)'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_matching_sessions', to=settings.AUTH_USER_MODEL)),
                ('matched_movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_in_sessions', to='movies.movie')),
                ('participants', models.ManyToManyField(blank=True, related_name='matching_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matching_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('likes_count', models.IntegerField(default=0)),
                ('match_percentage', models.FloatField(default=0.0)),
                ('matched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='movies.movie')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='matching.matchingsession')),
            ],
            options={
                'db_table': 'match_results',
                'ordering': ['-match_percentage', '-matched_at'],
                'unique_together': {('session', 'movie')},
            },
        ),
        migrations.CreateModel(
            name='MovieSwipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('liked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to='movies.movie')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to='matching.matchingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_swipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movie_swipes',
                'indexes': [models.Index(fields=['session', 'movie'], name='movie_swipe_session_1a2c31_idx'), models.Index(fields=['user', 'session'], name='movie_swipe_user_id_e22fd7_idx')],
                'unique_together': {('session', 'user', 'movie')},
            },
        ),
    ]
