# Generated by Django 5.2.8 on 2025-11-23 07:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('selected_genres', models.JSONField(default=list)),
                ('theme', models.CharField(blank=True, max_length=100)),
                ('release_year_min', models.IntegerField(blank=True, null=True)),
                ('release_year_max', models.IntegerField(blank=True, null=True)),
                ('max_runtime', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sessions', to=settings.AUTH_USER_MODEL)),
                ('matched_movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_in_sessions', to='movies.movie')),
                ('participants', models.ManyToManyField(related_name='matching_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matching_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_percentage', models.FloatField()),
                ('matched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('matched_users', models.ManyToManyField(related_name='matched_movies', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='matching.matchingsession')),
            ],
            options={
                'db_table': 'match_results',
                'ordering': ['-match_percentage', '-matched_at'],
                'unique_together': {('session', 'movie')},
            },
        ),
        migrations.CreateModel(
            name='MovieSwipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swipe_direction', models.CharField(choices=[('right', 'Right (Like)'), ('left', 'Left (Pass)')], max_length=10)),
                ('swiped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to='matching.matchingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_swipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movie_swipes',
                'indexes': [models.Index(fields=['session', 'movie'], name='movie_swipe_session_1a2c31_idx')],
                'unique_together': {('session', 'user', 'movie')},
            },
        ),
    ]
