# Generated by Django 5.2.8 on 2025-11-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='shared_content_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='typingstatus',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
