# Generated by Django 5.2.8 on 2025-11-23 07:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tmdb_id', models.IntegerField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('original_title', models.CharField(blank=True, max_length=200)),
                ('overview', models.TextField()),
                ('poster_path', models.CharField(blank=True, max_length=200)),
                ('backdrop_path', models.CharField(blank=True, max_length=200)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('genres', models.JSONField(default=list)),
                ('original_language', models.CharField(max_length=10)),
                ('tmdb_vote_average', models.FloatField(default=0)),
                ('tmdb_vote_count', models.IntegerField(default=0)),
                ('app_rating_average', models.FloatField(default=0)),
                ('app_rating_count', models.IntegerField(default=0)),
                ('watch_count', models.IntegerField(default=0)),
                ('interested_count', models.IntegerField(default=0)),
                ('is_upcoming', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'movies',
                'ordering': ['-release_date'],
                'indexes': [models.Index(fields=['tmdb_id'], name='movies_tmdb_id_472987_idx'), models.Index(fields=['release_date'], name='movies_release_e1d0b4_idx'), models.Index(fields=['is_upcoming'], name='movies_is_upco_a421c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_default', models.BooleanField(default=False)),
                ('privacy', models.CharField(choices=[('everyone', 'Everyone'), ('followers', 'Followers Only'), ('friends', 'Friends Only'), ('private', 'Private')], default='friends', max_length=20)),
                ('is_collaborative', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborative_watchlists', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'watchlists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMovieInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_watched', models.BooleanField(default=False)),
                ('is_liked', models.BooleanField(default=False)),
                ('is_interested', models.BooleanField(default=False)),
                ('rating', models.CharField(blank=True, choices=[('trash', 'Trash'), ('timepass', 'Timepass'), ('worth', 'Worth the Clock'), ('peak', 'Peak')], max_length=20, null=True)),
                ('watched_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_movie_interactions',
                'indexes': [models.Index(fields=['user', 'is_watched'], name='user_movie__user_id_337a5a_idx'), models.Index(fields=['user', 'rating'], name='user_movie__user_id_356403_idx')],
                'unique_together': {('user', 'movie')},
            },
        ),
        migrations.CreateModel(
            name='WatchlistMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, max_length=200)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movies.watchlist')),
            ],
            options={
                'db_table': 'watchlist_movies',
                'ordering': ['-added_at'],
                'unique_together': {('watchlist', 'movie')},
            },
        ),
    ]
